name: sampleplugin
main: dr.snow.sampleplugin.SamplePlugin
version: 1.1
api-version: 1.18

commands:
  heal:
    description: healing command


libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10